"""Add column description

Revision ID: 7bdbb3edb2d1
Revises: d04f6bd66d68
Create Date: 2024-04-13 01:13:53.682064

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bdbb3edb2d1"
down_revision = "d04f6bd66d68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizer",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizer", "description")
    # ### end Alembic commands ###
