"""Add table test

Revision ID: 547f1b6fc6a5
Revises: 70784cac6f77
Create Date: 2024-04-12 23:28:24.402379

"""


# revision identifiers, used by Alembic.
revision = "547f1b6fc6a5"
down_revision = "70784cac6f77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
