"""Add column xxx

Revision ID: 70784cac6f77
Revises: 394e64102884
Create Date: 2024-04-12 23:23:50.508616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70784cac6f77"
down_revision = "394e64102884"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("xxxx", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "xxxx")
    # ### end Alembic commands ###
