"""Add co

Revision ID: d04f6bd66d68
Revises: 547f1b6fc6a5
Create Date: 2024-04-13 00:45:52.377200

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "d04f6bd66d68"
down_revision = "547f1b6fc6a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizer",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superorganizer", sa.Boolean(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organizer_email"), "organizer", ["email"], unique=True)
    op.create_table(
        "event",
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["organizer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("user", "xxxx")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("xxxx", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_table("event")
    op.drop_index(op.f("ix_organizer_email"), table_name="organizer")
    op.drop_table("organizer")
    # ### end Alembic commands ###
