# このYAMLファイルは、GitHub Actionsのワークフロー定義で、masterブランチのプルリクエストが閉じられたとき、またはワークフローが手動でトリガーされたときに、最新の変更を取得します。
# ワークフロー名は"Latest Changes"です。
# このワークフローは、masterブランチのプルリクエストが閉じられたとき、またはワークフローが手動でトリガーされたときに開始されます。
# 手動でトリガーする場合、プルリクエストの番号とデバッグが有効かどうかを指定する必要があります。
# "latest-changes"ジョブは、最新のUbuntuランナーで実行されます。
# ジョブのステップでは、まずGitHubのコンテキストをダンプします。次に、GitHubのリポジトリをチェックアウトします。その後、tiangolo/latest-changesアクションを使用して最新の変更を取得します。このアクションは、リリースノートを更新し、最新の変更を記録します。
# このワークフローにより、プルリクエストが閉じられたときや手動でトリガーされたときに、最新の変更を自動的に取得し、リリースノートを更新することができます。

name: Latest Changes  # ワークフローの名前を定義します。

on:  # このワークフローがトリガーされるイベントを定義します。
  pull_request_target:  # pull_request_targetイベントがトリガーとなります。
    branches:
      - master  # masterブランチに対するプルリクエストでワークフローが開始されます。
    types:
      - closed  # プルリクエストが閉じられたときにワークフローが開始されます。
  workflow_dispatch:  # workflow_dispatchイベントがトリガーとなります。これにより、ワークフローを手動で実行することができます。
    inputs:
      number:
        description: PR number  # プルリクエストの番号を指定します。
        required: true  # この入力は必須です。
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'  # tmateデバッグを有効にしてビルドを実行するかどうかを指定します。
        required: false  # この入力は必須ではありません。
        default: 'false'  # デフォルトではtmateデバッグは無効になっています。

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}  # GitHubのコンテキストをJSON形式で出力します。
        run: echo "$GITHUB_CONTEXT"  # GitHubのコンテキストを表示します。
      - uses: actions/checkout@v4  # GitHubのリポジトリをチェックアウトします。
        with:
          # To allow latest-changes to commit to the main branch
          token: ${{ secrets.FULL_STACK_FASTAPI_POSTGRESQL_LATEST_CHANGES }}  # GitHubのシークレットからトークンを取得します。
      - uses: docker://tiangolo/latest-changes:0.3.0  # tiangolo/latest-changesアクションを使用します。
      # - uses: tiangolo/latest-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHubのトークンを使用します。
          latest_changes_file: ./release-notes.md  # 最新の変更を記録するファイルを指定します。
          latest_changes_header: '## Latest Changes'  # 最新の変更を記録するセクションのヘッダーを指定します。
          end_regex: '^## '  # 新しいエントリを追加する前に検索する正規表現を指定します。
          debug_logs: true  # デバッグログを有効にします。
          label_header_prefix: '### '  # ラベルのヘッダーのプレフィックスを指定します。